port: 80
db:
    host: localhost
    user: postgres
    password: postgres
    database: postgres
university:
    itemsPerPage: 5
subject:
    itemsPerPage: 5
material:
    itemsPerPage: 5
    files:
        directory: ./files/
icons:
    directory: ./icons
auth:
    secret_key: 12345
    # In seconds
    exp_time: 7200