version: "3.7"
services:
  server:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: ./db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./db/backup:/backup"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    